#!/bin/sh
#
# Copyright (C) 2011 OpenWrt.org
#

. /lib/functions/uci-defaults.sh
. /lib/ramips.sh

board=$(ramips_board_name)

case "$board" in
rl-s4005ef)
	ucidef_set_led_timer "system" "system" "richerlink:green:system" "500" "300"
	;;
esac

ucidef_commit_leds

exit 0
