#!/bin/sh
#
# Copyright (C) 2011 OpenWrt.org
#

[ -e /etc/config/network ] && exit 0

touch /etc/config/network

. /lib/functions/uci-defaults.sh
. /lib/ramips.sh

ucidef_set_interface_loopback

board=$(ramips_board_name)

case "$board" in

rl-s4005ef) 
#	ucidef_set_interfaces_lan_wan "eth1_0 eth1_1 eth1_2 eth1_3" "eth0"
	ucidef_set_interface_lan "eth1_0 eth1_1 eth1_2 eth1_3 ra0 ra1"
#	ucidef_set_interfaces_lan_wan "eth0.1" "eth0.2"
	ucidef_add_switch "switch0" "1" "1"
	ucidef_add_switch_vlan "switch0" "1" "0 1 2 3 4 6"
	ucidef_add_switch_vlan "switch0" "2" "5 6"
	;;
*)
	ucidef_set_interfaces_lan_wan "eth0" "eth1"
	;;
esac

uci commit network

exit 0
