#!/bin/sh /etc/rc.common
# Copyright (C) 2010 OpenWrt.org

START=80
STOP=10

# igmpproxy supports both a debug mode and verbosity, which are very useful
# when something isn't working.
#
# Debug mode will print everything to stdout instead of syslog. Generally
# verbosity should NOT be set as it will quickly fill your syslog.
#
# Put any debug or verbosity options into IGMP_OPTS
#
# Examples:
# IGMP_OPTS="-d -v -v" - debug mode and very verbose, this will land in
#                        stdout and not in syslog
# IGMP_OPTS="-v" - be verbose, this will write aditional information to syslog

IGMP_OPTS=""
IGMP_BIN="/usr/sbin/igmpproxy"
IGMP_CNF="/etc/igmpproxy.conf"
PID_F="/var/run/igmpproxy.pid"

igmp_start() {
    local cfg="$1"
    local IGMPEnable 

    config_get IGMPEnable "$cfg" IGMPEnable 

    if [ "$IGMPEnable" = "true" ] ; then
    	config_get igmpsnooping_enable "$cfg" SnoopingEnable
    	if [ -n $igmpsnooping_enable ] ; then 
        	if [ $igmpsnooping_enable = "true" ] ; then
		    echo 1 > /sys/class/net/br-lan/bridge/multicast_snooping
		    echo 1 > /sys/class/net/br1/bridge/multicast_snooping
        	fi
    	fi
    
    	config_get igmpproxy_enable "$cfg" ProxyEnable
    	if [ -n $igmpproxy_enable ] ; then
       		if [ $igmpproxy_enable = "true" ] ; then
		    start-stop-daemon -S -x $IGMP_BIN -p $PID_F -b -m -- $IGMP_OPTS $IGMP_CNF
       		fi
   	fi    
    fi
}

start() {
	config_load igmp
    config_foreach igmp_start IPTV

    [ -f /var/run/igmp.start ] || echo "start" > /var/run/igmp.start
}

stop() {
	echo 0 > /sys/class/net/br-lan/bridge/multicast_snooping
	echo 0 > /sys/class/net/br1/bridge/multicast_snooping
	start-stop-daemon -K -x $IGMP_BIN -p $PID_F -q
}
